=== gibson9583/oie-community-catalog/schemas/meta.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/gibson9583/oie-community-catalog/main/schemas/meta.schema.json",
    "title": "OIE Community Catalog package metadata (manifests/<id>/meta.json)",
    "type": "object",
    "required": ["id", "name", "description", "type", "publisher", "repository", "license"],
    "additionalProperties": true,
    "properties": {
        "id": {
            "description": "Stable package id (directory name). For extensions this MUST equal the plugin.xml path attribute.",
            "type": "string",
            "pattern": "^[a-z0-9][a-z0-9-]*$"
        },
        "name": { "type": "string", "minLength": 1 },
        "description": { "type": "string", "minLength": 1 },
        "type": {
            "type": "string",
            "enum": ["plugin", "connector", "datatype", "channel", "code-template", "code-template-library"]
        },
        "publisher": { "type": "string", "minLength": 1 },
        "repository": { "type": "string", "format": "uri", "description": "Source repository URL (any forge)." },
        "homepage": { "type": "string", "format": "uri" },
        "documentation": { "type": "string", "format": "uri" },
        "license": { "type": "string", "description": "SPDX identifier or expression." },
        "authors": { "type": "array", "items": { "type": "string" } },
        "keywords": { "type": "array", "items": { "type": "string" } },
        "deprecated": { "type": "boolean", "default": false },
        "deprecationMessage": { "type": "string" },
        "contentId": {
            "description": "REQUIRED for channel / code-template / code-template-library packages: the engine id (UUID) inside the artifact, used for installed-detection.",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        }
    }
}

=== gibson9583/oie-community-catalog/manifests/plugins/simple-channel-history/meta.json
{
    "id": "simple-channel-history",
    "name": "Simple Channel History",
    "description": "Version history for channels and code templates: automatic revision tracking on save, a decomposed side-by-side component diff, revert and prune, deleted-item XML snapshots, and a Deleted Items settings tab. Works in both the Swing and web administrators.",
    "type": "plugin",
    "publisher": "Diridium Technologies Inc.",
    "repository": "https://github.com/gibson9583/simple-channel-history",
    "homepage": "https://github.com/gibson9583/simple-channel-history",
    "documentation": "https://github.com/gibson9583/simple-channel-history#readme",
    "license": "MPL-2.0",
    "authors": [
        "Diridium Technologies Inc.",
        "Kiran Ayyagari"
    ],
    "keywords": [
        "history",
        "versioning",
        "channels",
        "code-templates",
        "diff",
        "revert",
        "audit"
    ],
    "deprecated": false
}

=== gibson9583/oie-community-catalog/manifests/channels/example-validate-xsd-source-filter/meta.json
{
    "id": "example-validate-xsd-source-filter",
    "name": "Validate XSD Source Filter",
    "description": "Example channel: Validate XSD Source Filter.",
    "type": "channel",
    "publisher": "NextGen Healthcare",
    "repository": "https://github.com/gibson9583/connect-examples",
    "homepage": "https://github.com/gibson9583/connect-examples",
    "documentation": "https://github.com/gibson9583/connect-examples/blob/master/Channels/Validate%20XSD%20Source%20Filter/README.md",
    "license": "MPL-2.0",
    "authors": [
        "NextGen Healthcare"
    ],
    "keywords": [
        "example",
        "channel"
    ],
    "deprecated": false,
    "contentId": "9c5f43ca-544c-4a40-80f6-455868c7e3f4"
}

=== gibson9583/oie-community-catalog/manifests/plugins/tls-manager/meta.json
{
    "id": "tls-manager",
    "name": "TLS Manager",
    "description": "TLS-enabled networking connectors and a certificate management view for Open Integration Engine.",
    "type": "plugin",
    "publisher": "NovaMap Health",
    "repository": "https://github.com/gibson9583/tls-manager-plugin",
    "homepage": "https://github.com/gibson9583/tls-manager-plugin",
    "documentation": "https://github.com/gibson9583/tls-manager-plugin#readme",
    "license": "Apache-2.0 OR MPL-2.0",
    "authors": [
        "NovaMap Health"
    ],
    "keywords": [
        "tls",
        "ssl",
        "certificate",
        "mtls",
        "security",
        "connector"
    ],
    "deprecated": false
}

=== gibson9583/oie-community-catalog/manifests/code-templates/ct-encrypt-pdf/meta.json
{
    "id": "ct-encrypt-pdf",
    "name": "Encrypt PDF",
    "description": "Example code template: Encrypt PDF.",
    "type": "code-template",
    "publisher": "NextGen Healthcare",
    "repository": "https://github.com/gibson9583/connect-examples",
    "homepage": "https://github.com/gibson9583/connect-examples",
    "documentation": "https://github.com/gibson9583/connect-examples/blob/master/Code%20Templates/Encrypt%20PDF/README.md",
    "license": "MPL-2.0",
    "authors": [
        "Nick Rupley"
    ],
    "keywords": [
        "example",
        "code template"
    ],
    "deprecated": false,
    "contentId": "942f9161-6998-42e1-9528-83342f457ac5"
}

=== gibson9583/oie-community-catalog/manifests/channels/example-get-num-pages-from-embedded-pdf/meta.json
{
    "id": "example-get-num-pages-from-embedded-pdf",
    "name": "Get Num Pages From Embedded PDF",
    "description": "Example channel: Get Num Pages From Embedded PDF.",
    "type": "channel",
    "publisher": "NextGen Healthcare",
    "repository": "https://github.com/gibson9583/connect-examples",
    "homepage": "https://github.com/gibson9583/connect-examples",
    "documentation": "https://github.com/gibson9583/connect-examples/blob/master/Channels/Get%20Num%20Pages%20From%20Embedded%20PDF/README.md",
    "license": "MPL-2.0",
    "authors": [
        "Nick Rupley"
    ],
    "keywords": [
        "example",
        "channel"
    ],
    "deprecated": false,
    "contentId": "6de4dab6-cbb8-4840-87bb-31a85fab9101"
}

=== gibson9583/oie-community-catalog/manifests/code-templates/ct-join-hl7-subcomponents/meta.json
{
    "id": "ct-join-hl7-subcomponents",
    "name": "Join HL7 Subcomponents",
    "description": "Example code template: Join HL7 Subcomponents.",
    "type": "code-template",
    "publisher": "NextGen Healthcare",
    "repository": "https://github.com/gibson9583/connect-examples",
    "homepage": "https://github.com/gibson9583/connect-examples",
    "documentation": "https://github.com/gibson9583/connect-examples/blob/master/Code%20Templates/Join%20HL7%20Subcomponents/README.md",
    "license": "MPL-2.0",
    "authors": [
        "Tony Germano"
    ],
    "keywords": [
        "example",
        "code template"
    ],
    "deprecated": false,
    "contentId": "aab23d47-cae1-4a03-9317-27246e5cf808"
}

=== gibson9583/oie-community-catalog/manifests/code-templates/ct-unescape-xdd-hl7-sequences/meta.json
{
    "id": "ct-unescape-xdd-hl7-sequences",
    "name": "Unescape Xdd HL7 Sequences",
    "description": "Example code template: Unescape Xdd HL7 Sequences.",
    "type": "code-template",
    "publisher": "NextGen Healthcare",
    "repository": "https://github.com/gibson9583/connect-examples",
    "homepage": "https://github.com/gibson9583/connect-examples",
    "documentation": "https://github.com/gibson9583/connect-examples/blob/master/Code%20Templates/Unescape%20Xdd%20HL7%20Sequences/README.md",
    "license": "MPL-2.0",
    "authors": [
        "NextGen Healthcare"
    ],
    "keywords": [
        "example",
        "code template"
    ],
    "deprecated": false,
    "contentId": "9d3f1dd9-d28e-42e5-89bd-8a3569b33b69"
}

=== gibson9583/oie-community-catalog/manifests/code-templates/ct-convert-date-from-multiple-formats/meta.json
{
    "id": "ct-convert-date-from-multiple-formats",
    "name": "Convert Date From Multiple Formats",
    "description": "Example code template: Convert Date From Multiple Formats.",
    "type": "code-template",
    "publisher": "NextGen Healthcare",
    "repository": "https://github.com/gibson9583/connect-examples",
    "homepage": "https://github.com/gibson9583/connect-examples",
    "documentation": "https://github.com/gibson9583/connect-examples/blob/master/Code%20Templates/Convert%20Date%20From%20Multiple%20Formats/README.md",
    "license": "MPL-2.0",
    "authors": [
        "NextGen Healthcare"
    ],
    "keywords": [
        "example",
        "code template"
    ],
    "deprecated": false,
    "contentId": "e31ef05e-7cd5-43d2-a2db-b264ed98c003"
}
